language: java 
jdk:
  - oraclejdk8s
sudo: required
env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "EzATNizBcHCGwTy4EqQneoiRqxqT5QlGcYlbglg+Z5nlt0EYbD3tgAJDYupGS3iSsGcStIx5BK5PM9aWkcuUOVoi+4bc4qhHV5p1mQ9EJ6BKNrh2UE5AT1NGfrYmWZuv3MbmAPsEVNjFgW8hCOd/qhzZcOl1G6muiBH2Dx8543HgyQ3ZO3SHALqi1W95HRO6dgKZcKIIB9VCli6/ftyieu4xBxr5GjhJkneMBPEvJktYgbV9Qis1IDEp50f5CocQydYVewg6bVhMua+w4apFbQrWZfMWDwCZxnEyoqUosm7Ysij+Vjki+CwE/s+fpgzCwMiwNN/8ODaBxEBJgwiE81HxNwfnMsvj/bfVIGuLEwzAbFsvpbzZi88bcpBoNxKB31yOxGVqRZ+1DRcQfw97UIGYLKv6UMqLsu3Ixc18mRKSszU9T8JJGDPs9P/wZe6/8av8nqhtQLSmIufrZ5Qr5hbRj2qtvTzFVLFEp0tm901RrEF9znbEqnXL2Dg/HOPU6CLuy6XTHDb/K1Q8qY0qZdS1TXiF8vOegl1iyG+wG2K5dfgnvjrXJqH2OnC5iKLi5uHckWe5X+SH+0rVjAaEkaTtpMdCmO3SRR4gVXM/Y7V2Wm3fFANj64vjI2qfs4+GL+BMbXYwe7CQ0oduji6oK2BpxcvZbinO0llDMEyxpa8="

before_install:
      - echo -n | openssl s_client -connect scan.coverity.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-

addons:
  coverity_scan:
    project:
      name: "teverett/OLMReader"
      description: "Build submitted via Travis CI"
    notification_email: tom@khubla.com
    build_command_prepend: "mvn clean"
    build_command:   "mvn -DskipTests=true compile"
    branch_pattern: coverity_scan
    